imageCredentials:
  create: false
  name: aqua-registry-secret # When create is false please specify
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""

docker:
  socket:
    path: "/var/run/docker.sock" # pks - /var/vcap/data/sys/run/docker/docker.sock

docker:

server:
  serviceName: "aqua-console-svc" # example
  port: 8080

image:
  repository: scanner
  tag: "5.0"
  pullPolicy: IfNotPresent

user:
password:
replicaCount: 1
livenessProbe: {}
readinessProbe: {}
resources: {}
  # Note: For recommendations please check the official sizing guide.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
